#!/usr/bin/env bash
# Generates Sources/NextNotes/Formatting/LLM/LlamaArchitectures.swift from the llama.cpp
# tag pinned in Package.swift, and cross-checks every name against the linked binary.
#
# Usage:
#   Scripts/gen-llama-architectures.sh          rewrite the generated file
#   Scripts/gen-llama-architectures.sh --check  fail if the committed file has drifted
#
# The architecture table is the source of truth for what this build can open; a name that
# is in the source but not in the binary would refuse a model the app can actually run, so
# a miss is a hard failure rather than a warning.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
PACKAGE="$ROOT/Package.swift"
OUTPUT="$ROOT/Sources/NextNotes/Formatting/LLM/LlamaArchitectures.swift"
BINARY="${LLAMA_FRAMEWORK_BINARY:-$HOME/Library/Caches/NextNotesBuild/scratch/out/Products/Debug/llama.framework/Versions/A/llama}"

TAG=$(grep -oE 'download/b[0-9]+/' "$PACKAGE" | grep -oE 'b[0-9]+' | head -1 || true)
if [[ -z "$TAG" ]]; then
  echo "gen-llama-architectures: no LlamaFramework tag found in Package.swift" >&2
  exit 1
fi

if [[ ! -f "$BINARY" ]]; then
  echo "gen-llama-architectures: $BINARY is missing; run make build first" >&2
  exit 1
fi

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

curl -fsSL "https://raw.githubusercontent.com/ggml-org/llama.cpp/$TAG/src/llama-arch.cpp" \
  -o "$WORK/llama-arch.cpp"

# `{ LLM_ARCH_X, "name" }` rows, minus the two non-models: `clip` is a dummy row and
# `(unknown)` is the fallback. LC_ALL=C so the order does not follow the machine's locale.
grep -oE '\{ LLM_ARCH_[A-Z0-9_]+,\s*"[^"]+"' "$WORK/llama-arch.cpp" \
  | sed -E 's/.*"([^"]+)"/\1/' \
  | grep -v -x -e clip -e '(unknown)' \
  | LC_ALL=C sort -u > "$WORK/names.txt"

if [[ ! -s "$WORK/names.txt" ]]; then
  echo "gen-llama-architectures: the architecture table at $TAG came back empty" >&2
  exit 1
fi

# `-n 2` is load-bearing: strings defaults to a minimum length of 4, and three real names
# (`mpt`, `plm`, `t5`) are shorter, so the default reports them missing from a binary that
# contains them.
strings -a -n 2 "$BINARY" > "$WORK/binary-strings.txt"
MISSES=""
while IFS= read -r name; do
  grep -Fxq "$name" "$WORK/binary-strings.txt" || MISSES="$MISSES $name"
done < "$WORK/names.txt"
if [[ -n "$MISSES" ]]; then
  echo "gen-llama-architectures: $TAG lists architectures this binary does not contain:$MISSES" >&2
  exit 1
fi

{
  echo "// Generated by Scripts/gen-llama-architectures.sh from llama.cpp $TAG src/llama-arch.cpp."
  echo "// Do not edit by hand. Regenerate whenever Package.swift's LlamaFramework tag changes."
  echo "enum LlamaArchitectures {"
  echo "    static let buildTag = \"$TAG\""
  printf '    static let supported: Set<String> = ['
  awk '{ printf "%s\"%s\"", (NR > 1 ? ", " : ""), $0 }' "$WORK/names.txt"
  echo "]"
  echo "    static func isSupported(_ architecture: String) -> Bool { supported.contains(architecture.lowercased()) }"
  echo "}"
} > "$WORK/LlamaArchitectures.swift"

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "$OUTPUT" "$WORK/LlamaArchitectures.swift"; then
    echo "gen-llama-architectures: LlamaArchitectures.swift is out of date; run Scripts/gen-llama-architectures.sh" >&2
    exit 1
  fi
  echo "gen-llama-architectures: no drift"
  exit 0
fi

cp "$WORK/LlamaArchitectures.swift" "$OUTPUT"
echo "gen-llama-architectures: wrote $OUTPUT ($(wc -l < "$WORK/names.txt" | tr -d ' ') architectures, $TAG)"
